services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
      - prometheus
    volumes:
      - ./model.pkl:/app/model.pkl

  mlflow:
    build:
      context: ./mlflow
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - mlflow-artifacts:/mlflow-artifacts
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000

  training:
    build:
      context: .
      dockerfile: Dockerfile.training
    volumes:
      - ./data:/train/data
      - ./model.pkl:/train/model.pkl
    depends_on:
      - mlflow

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./data:/monitor/data
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  prefect-server:
    build:
      context: ./prefect
    ports:
      - "4200:4200"
    environment:
      PREFECT_API_DATABASE_CONNECTION_URL: postgresql+asyncpg://postgres:password@backend-database:5432/prefect_db
      



volumes:
  mongo_data:
  grafana-storage:
  pgdata:
  mlflow-artifacts:
